package potato

var fallbackURLs = []string{
	"https://i.imgur.com/7UhJCiR.jpeg",
	"https://i.imgur.com/3Y1QXWK.jpeg",
	"https://i.imgur.com/8bFjQGV.jpeg",
	"https://i.imgur.com/ZxJGPVo.jpeg",
	"https://i.imgur.com/5mFGKqN.jpeg",
	"https://i.imgur.com/Q9Xnv8r.jpeg",
	"https://i.imgur.com/VJlMz8C.jpeg",
	"https://i.imgur.com/kWjlGUy.jpeg",
	"https://i.imgur.com/2HxLMhN.jpeg",
	"https://i.imgur.com/RYqpRoL.jpeg",
	"https://i.imgur.com/pTkG6Ck.jpeg",
	"https://i.imgur.com/4fMjKYa.jpeg",
	"https://i.imgur.com/WnDqSBR.jpeg",
	"https://i.imgur.com/hXBmpBN.jpeg",
	"https://i.imgur.com/JfKt5qA.jpeg",
	"https://i.imgur.com/LmNOpQr.jpeg",
	"https://i.imgur.com/StUvWxY.jpeg",
	"https://i.imgur.com/AbCdEfG.jpeg",
	"https://i.imgur.com/HiJkLmN.jpeg",
	"https://i.imgur.com/OpQrStU.jpeg",
	"https://i.imgur.com/VwXyZaB.jpeg",
	"https://i.imgur.com/CdEfGhI.jpeg",
	"https://i.imgur.com/JkLmNpQ.jpeg",
	"https://i.imgur.com/RsTuVwX.jpeg",
	"https://i.imgur.com/YzAbCdE.jpeg",
	"https://i.imgur.com/FgHiJkL.jpeg",
	"https://i.imgur.com/MnOpQrS.jpeg",
	"https://i.imgur.com/TuVwXyZ.jpeg",
	"https://i.imgur.com/1aBcDeF.jpeg",
	"https://i.imgur.com/2gHiJkL.jpeg",
}
